export const bankBilletFactory = {
  id: 305363,
  expire_at: '2030-05-04',
  paid_at: null,
  description: 'Boleto para Renata Céli',
  status: 'opened',
  recipient_account: null,
  reduction_amount: null,
  instructions_mode: null,
  import_id: null,
  virtual_bank_billet_id: null,
  shorten_url: 'https://bole.to/3/lldyfg',
  customer_person_type: 'individual',
  customer_person_name: 'Renata M',
  customer_cnpj_cpf: '662.174.373-41',
  customer_address: 'Avenida Rui Barbosa',
  customer_state: 'RJ',
  customer_neighborhood: 'São Francisco',
  customer_zipcode: '24360440',
  customer_address_number: '',
  customer_address_complement: '',
  customer_phone_number: '1122222222',
  customer_email: 'user@gmail.com',
  customer_email_cc: 'user+cc@gmail.com',
  customer_ignore_email: null,
  customer_ignore_sms: null,
  customer_mobile_local_code: null,
  customer_mobile_number: null,
  customer_nickname: 'Renatinha',
  customer_notes: null,
  created_via_api: false,
  customer_city_name: 'Niterói',
  paid_amount: 0,
  amount: 120.5,
  url: 'https://bole.to/3/lldyfg',
  formats: {
    default: 'https://bole.to/3/lldyfg',
    png: 'https://bole.to/3/lldyfg.png?r=1587682151',
    pdf: 'https://bole.to/3/lldyfg.pdf?r=1587682151',
    barcode: 'https://bole.to/3/lldyfg/barcode',
    envelope: 'https://bole.to/3/lldyfg/envelope',
    letter: 'https://bole.to/3/lldyfg/letter',
    line: 'https://bole.to/3/lldyfg/line',
    recibo: 'https://bole.to/3/lldyfg/recibo',
  },
  meta: null,
  fine_for_delay: null,
  fine_type: 0,
  fine_percentage: null,
  fine_value: null,
  days_for_fine: null,
  late_payment_interest: null,
  interest_type: 0,
  interest_daily_value: null,
  interest_daily_percentage: null,
  interest_monthly_percentage: null,
  days_for_interest: null,
  discount_type: 0,
  discount_limit_date: null,
  discount_value: null,
  discount_percentage: null,
  days_for_revoke: null,
  days_for_negativation: null,
  notes: null,
  payment_count: 1,
  bank_billet_account_id: 122,
  beneficiary_name: 'Rafael Henrique',
  beneficiary_cnpj_cpf: '034.448.058-53',
  beneficiary_address: 'Avenida Rui Barbosa, 999, 999, 24360-440',
  beneficiary_assignor_code: '1690-P / 0000097-3',
  beneficiary_contract_slug: null,
  guarantor_name: '',
  guarantor_cnpj_cpf: null,
  payment_place: 'Pagável em qualquer banco até a data de vencimento.',
  watermark: null,
  instructions: 'Não receber após o vencimento',
  document_date: null,
  document_type: '02',
  document_number: '',
  acceptance: 'N',
  processed_our_number: '06/00000000071-1',
  processed_our_number_raw: '06000000000711',
  bank_contract_slug: 'bradesco-bs-06',
  agency_number: '1690',
  agency_digit: '0',
  account_number: '0000097',
  account_digit: '3',
  registration_status: null,
  extra1: null,
  extra1_digit: null,
  extra2: null,
  extra2_digit: null,
  line: '23791.69002 60000.000004 71000.009705 1 82450000012050',
  our_number: '00000000071',
  customer_subscription_id: null,
  installment_number: null,
  installment_total: null,
  installment_id: null,
  carne_url: null,
  pix_enabled: null,
  pix_qrcode: null,
  pix_txid: null,
  prevent_pix: null,
  bank_billet_layout_id: null,
  remittance_id: null,
  created_at: '2020-04-23T19:49:09-03:00',
  updated_at: '2020-04-23T19:49:11-03:00',
  tags: [],
  tag_list: '',
  document_type_label: 'DM',
  addons: null,
  ignore_email: false,
  ignore_sms: null,
  ignore_whatsapp: null,
  sue_code: null,
  revoke_code: null,
  first_instruction: null,
  second_instruction: null,
  guarantor_address_number: null,
  guarantor_neighborhood: null,
  guarantor_phone_number: null,
  guarantor_city_name: null,
  guarantor_state: null,
  guarantor_zipcode: null,
  guarantor_address: null,
  guarantor_address_complement: null,
  barcode: '23791824500000120501690060000000007100000970',
  registered_at: null,
  register_type: null,
  cancel_type: null,
  cancellation_reason: null,
  prevent_registration: false,
  customer_id: 2,
  control_number: null,
  divergent_payment_type: null,
  divergent_payment_value_type: null,
  divergent_payment_maximum_value: null,
  divergent_payment_minimum_value: null,
  divergent_payment_maximum_percentage: null,
  divergent_payment_minimum_percentage: null,
  divergent_payment_limit: null,
  days_for_discount: null,
  days_for_second_discount: null,
  second_discount_percentage: null,
  second_discount_value: null,
  days_for_third_discount: null,
  third_discount_percentage: null,
  third_discount_value: null,
  days_for_sue: null,
  interest_percentage: null,
  interest_value: null,
  interest_days_type: 0,
  customer_contact_person: null,
  custom_attachment_name: '',
  split_payment: false,
  dispatch_type: 1,
  charge_type: 1,
  bank_billet_discharges: [],
  bank_billet_remittances: [
    {
      id: 271882,
      our_code: '1001',
      occurrence: '01',
      remittance_id: null,
      bank_billet_id: 305363,
      bank_billet_account_id: 122,
      processed_at: null,
      occurrence_detail: 'Entrada de Título',
      created_at: '2020-04-23',
    },
  ],
  bank_billet_payments: [],
  bank_billet_registrations: [],
  bank_billet_split_accounts: [],
};
